import { useEffect, useMemo, useState } from 'react';
import {
  AlignLeft, ArrowLeftRight, BookOpen, Calculator, Check, ChevronDown, Copy,
  FlaskConical, Globe2, History, Info, Languages, Menu, Moon, Settings2,
  Shield, Sun, X,
} from 'lucide-react';

type Language = 'fr' | 'en' | 'es' | 'ar';
type Mode = 'basic' | 'scientific' | 'advanced';
type Screen = 'calculator' | 'history' | 'converter' | 'constants' | 'references' | 'about' | 'rules' | 'terms' | 'credits' | 'settings';
type HistoryEntry = { expression: string; result: string; id: string };

const words: Record<Language, Record<string, string>> = {
  fr: {
    calculator:'Calculatrice', subtitle:'Un instrument de calcul, tout simplement.', basic:'Mode basique', scientific:'Scientifique', advanced:'Avancé',
    tools:'Outils', information:'Informations',
    ready:'PRÊTE À CALCULER', angle:'ANGLE', degrees:'DEG', radians:'RAD', memory:'Calcul instantané', expression:'Expression',
    history:'Historique', clear:'Effacer', noHistory:'Votre historique est vide', historyHint:'Vos prochains calculs apparaîtront ici.',
    converter:'Conversions', convertHint:'Convertissez les unités courantes.', quantity:'Grandeur', from:'De', to:'Vers', value:'Valeur', result:'Résultat',
    length:'Longueur', mass:'Masse', temperature:'Température', volume:'Volume', time:'Temps',
    constants:'Constantes', constantsHint:'Touchez une constante pour l’insérer dans le calcul.',
    references:'Références', referencesText:'Quelques repères utiles pour vos calculs.',
    about:'À propos', rules:'Règles de calcul', terms:'Conditions d’utilisation', credits:'Crédits', settings:'Réglages',
    aboutText:'Adam Calculator est une calculatrice web personnelle pensée et créée par Adam Eddahbi. Un outil discret, rapide et fiable pour les calculs du quotidien, avec des fonctions scientifiques à portée de main. Tous les calculs et réglages restent dans votre navigateur.',
    rulesIntro:'La calculatrice suit les règles mathématiques usuelles, sans approximation cachée.',
    ruleOrder:'Ordre des opérations', ruleOrderText:'Les parenthèses sont évaluées en premier, puis les fonctions, les puissances, les multiplications et divisions, puis les additions et soustractions. Les puissances s’associent de droite à gauche.',
    rulePercent:'Pourcentages', rulePercentText:'Le symbole % transforme la valeur qui le précède en fraction sur 100. Par exemple, 25% vaut 0,25.',
    ruleAngles:'Angles', ruleAnglesText:'Les fonctions trigonométriques utilisent le mode DEG (degrés) par défaut. Basculez en RAD pour les radians.',
    ruleVerify:'Vérifiez les résultats', ruleVerifyText:'Vérifiez indépendamment tout résultat important avant de l’utiliser.',
    ruleResponsible:'Usage responsable', ruleResponsibleText:'Utilisez l’outil avec discernement et sous votre propre responsabilité.',
    ruleSecurity:'Utilisation du site', ruleSecurityText:'Toute tentative de perturber, d’endommager ou de contourner le fonctionnement du site est interdite.',
    termsText:'Adam Calculator est un outil personnel gratuit, et non un service fourni par une société. En utilisant le site, vous acceptez ces conditions. Vous pouvez utiliser la calculatrice pour des calculs personnels courants. Les résultats sont calculés localement et peuvent être inexacts ; vérifiez-les avant de vous y fier, en particulier dans un contexte professionnel, financier ou de sécurité. Le service est fourni sans garantie et son auteur décline toute responsabilité pour les conséquences de son utilisation, dans la mesure permise par la loi. Le nom, le contenu et le code du site restent soumis aux droits de leurs titulaires respectifs. Le service ou ces conditions peuvent évoluer sans préavis. Une disponibilité continue n’est pas garantie. Pour toute question, adressez-vous au créateur, Adam Eddahbi.',
    termsAcceptance:'Acceptation des conditions', termsAcceptanceText:'En utilisant le site, vous acceptez les présentes conditions.',
    termsUse:'Utilisation du service', termsUseText:'Vous pouvez utiliser la calculatrice pour des calculs personnels courants. Toute tentative de perturbation ou de contournement du site est interdite.',
    termsAccuracy:'Exactitude des résultats', termsAccuracyText:'Les résultats sont fournis à titre indicatif et peuvent comporter des erreurs ou des arrondis.',
    termsResponsibility:'Responsabilité', termsResponsibilityText:'Vérifiez les résultats importants. Dans la mesure permise par la loi, le créateur décline toute responsabilité liée à l’utilisation de l’outil.',
    termsIntellectual:'Propriété intellectuelle', termsIntellectualText:'Le nom, le contenu et le code sont protégés par les droits de leurs titulaires respectifs. Adam Calculator ne prétend pas être une société enregistrée.',
    termsChanges:'Modifications du service', termsChangesText:'Le service et ses conditions peuvent être modifiés afin de corriger ou d’améliorer l’application.',
    termsAvailability:'Disponibilité', termsAvailabilityText:'Le service est fourni gratuitement, sans garantie de fonctionnement continu ni de disponibilité.',
    termsContact:'Contact', termsContactText:'Pour toute question, contactez le créateur par le canal de projet Replit utilisé pour vous partager la calculatrice.',
    creditsText:'Adam Calculator — Créé par Adam Eddahbi. Réalisée avec soin pour le web, avec des outils open source. Merci de l’utiliser.',
    language:'Langue', appearance:'Apparence', darkMode:'Thème sombre', darkHint:'Une palette douce pour les environnements peu éclairés.',
    angleSetting:'Unité d’angle', clearHistory:'Effacer l’historique',
    animations:'Animations', animationsHint:'Transitions discrètes entre les interactions.', close:'Fermer', chooseLanguage:'Choisir une langue', light:'Clair', dark:'Sombre',
    errorSyntax:'Expression invalide', errorDivide:'Division par zéro impossible', errorDomain:'Valeur hors du domaine de définition', errorNumber:'Résultat non fini',
    copy:'Copier le résultat', copied:'Copié', clearEntry:'Effacer', delete:'Retour arrière', allClear:'Tout effacer', decimal:'Virgule',
    menu:'Ouvrir le menu', languageMenu:'Changer de langue', author:'Créé par Adam Eddahbi', copyright:'© 2026 Adam Calculator',
    sin:'sin', cos:'cos', tan:'tan', asin:'sin⁻¹', acos:'cos⁻¹', atan:'tan⁻¹', log:'log', ln:'ln', exp:'exp', sqrt:'√', square:'x²', power:'xʸ', inverse:'1/x', factorial:'n!', abs:'|x|', modulo:'mod', floor:'⌊x⌋', ceil:'⌈x⌉', round:'arrondi',
    pi:'Pi', euler:'Euler', sqrt2:'Racine de 2', phi:'Nombre d’or',
    lengthM:'Mètre', lengthKm:'Kilomètre', lengthCm:'Centimètre', lengthMi:'Mile', lengthFt:'Pied', lengthIn:'Pouce',
    massKg:'Kilogramme', massG:'Gramme', massLb:'Livre', massOz:'Once',
    tempC:'Celsius', tempF:'Fahrenheit', tempK:'Kelvin',
    volL:'Litre', volMl:'Millilitre', volM3:'Mètre cube', volGal:'Gallon US',
    timeS:'Seconde', timeMin:'Minute', timeH:'Heure', timeDay:'Jour',
    referencePi:'π ≈ 3,141592653589793 — rapport du périmètre d’un cercle à son diamètre.',
    referenceE:'e ≈ 2,718281828459045 — base des logarithmes naturels.',
    referenceGolden:'φ ≈ 1,618033988749895 — nombre d’or, solution positive de x² − x − 1 = 0.',
    referenceConversions:'1 pouce = 2,54 cm · 1 mile = 1,609344 km · 1 livre = 0,45359237 kg.',
    referenceSin:'sin(x) — sinus de l’angle x.',
    referenceCos:'cos(x) — cosinus de l’angle x.',
    referenceTan:'tan(x) — tangente de l’angle x.',
    referenceLog:'log(x) — logarithme décimal (base 10).',
    referenceLn:'ln(x) — logarithme naturel (base e).',
    referenceSquare:'x² — carré de x, soit x multiplié par lui-même.',
    referenceSqrt:'√x — racine carrée principale de x.',
    referencePower:'xʸ — x élevé à la puissance y.',
    referenceAngles:'Les angles sont en degrés (DEG) ou radians (RAD), selon le réglage.',
  },
  en: {
    calculator:'Calculator', subtitle:'A considered instrument for everyday math.', basic:'Basic mode', scientific:'Scientific', advanced:'Advanced',
    tools:'Tools', information:'Information',
    ready:'READY WHEN YOU ARE', angle:'ANGLE', degrees:'DEG', radians:'RAD', memory:'Instant calculation', expression:'Expression',
    history:'History', clear:'Clear', noHistory:'Your history is clear', historyHint:'Your next calculations will appear here.',
    converter:'Conversions', convertHint:'Convert everyday units with ease.', quantity:'Quantity', from:'From', to:'To', value:'Value', result:'Result',
    length:'Length', mass:'Mass', temperature:'Temperature', volume:'Volume', time:'Time',
    constants:'Constants', constantsHint:'Select a constant to insert it into your calculation.',
    references:'References', referencesText:'A few useful points of reference.',
    about:'About', rules:'Calculation rules', terms:'Terms of service', credits:'Credits', settings:'Settings',
    aboutText:'Adam Calculator is a personal web calculator designed and built by Adam Eddahbi. A quiet, quick, dependable tool for everyday arithmetic, with scientific functions close at hand. Your calculations and settings stay in your browser.',
    rulesIntro:'The calculator follows familiar mathematical conventions, with no hidden approximation.',
    ruleOrder:'Order of operations', ruleOrderText:'Parentheses are evaluated first, followed by functions, powers, multiplication and division, then addition and subtraction. Powers associate from right to left.',
    rulePercent:'Percentages', rulePercentText:'The % symbol converts the preceding value to a fraction out of 100. For example, 25% is 0.25.',
    ruleAngles:'Angles', ruleAnglesText:'Trigonometric functions use DEG (degrees) by default. Switch to RAD for radians.',
    ruleVerify:'Check important results', ruleVerifyText:'Independently verify important results before relying on them.',
    ruleResponsible:'Responsible use', ruleResponsibleText:'Use the tool thoughtfully and at your own discretion.',
    ruleSecurity:'Use of the site', ruleSecurityText:'Attempts to disrupt, damage, or bypass the site are prohibited.',
    termsText:'Adam Calculator is a free personal tool, not a service provided by a company. By using the site, you accept these terms. You may use the calculator for ordinary personal calculations. Results are computed locally and may be inaccurate; verify them before relying on them, especially in professional, financial, or safety-critical settings. The service is provided without warranties, and its creator disclaims liability for consequences of use to the extent permitted by law. The site name, content, and code remain subject to the rights of their respective owners. The service or these terms may change without notice. Continuous availability is not guaranteed. For questions, contact its creator, Adam Eddahbi.',
    termsAcceptance:'Acceptance of terms', termsAcceptanceText:'By using the site, you agree to these terms.',
    termsUse:'Use of the service', termsUseText:'You may use the calculator for ordinary personal calculations. Attempts to disrupt or bypass the site are prohibited.',
    termsAccuracy:'Accuracy of results', termsAccuracyText:'Results are provided for guidance and may contain errors or rounding.',
    termsResponsibility:'Responsibility', termsResponsibilityText:'Verify important results. To the extent permitted by law, the creator disclaims liability related to use of the tool.',
    termsIntellectual:'Intellectual property', termsIntellectualText:'The name, content, and code are subject to the rights of their respective owners. Adam Calculator does not claim to be a registered company.',
    termsChanges:'Service changes', termsChangesText:'The service and its terms may change to correct or improve the application.',
    termsAvailability:'Availability', termsAvailabilityText:'The service is provided free of charge without a guarantee of continuous operation or availability.',
    termsContact:'Contact', termsContactText:'For questions, contact the creator through the Replit project channel used to share the calculator with you.',
    creditsText:'Adam Calculator — Created by Adam Eddahbi. Made with care for the web, using open-source tools. Thank you for using it.',
    language:'Language', appearance:'Appearance', darkMode:'Dark theme', darkHint:'A softer palette for low-light surroundings.',
    angleSetting:'Angle unit', clearHistory:'Clear history',
    animations:'Animations', animationsHint:'Subtle transitions between interactions.', close:'Close', chooseLanguage:'Choose a language', light:'Light', dark:'Dark',
    errorSyntax:'Invalid expression', errorDivide:'Cannot divide by zero', errorDomain:'Value outside the function domain', errorNumber:'Result is not finite',
    copy:'Copy result', copied:'Copied', clearEntry:'Clear', delete:'Backspace', allClear:'Clear all', decimal:'Decimal',
    menu:'Open menu', languageMenu:'Change language', author:'Created by Adam Eddahbi', copyright:'© 2026 Adam Calculator',
    sin:'sin', cos:'cos', tan:'tan', asin:'sin⁻¹', acos:'cos⁻¹', atan:'tan⁻¹', log:'log', ln:'ln', exp:'exp', sqrt:'√', square:'x²', power:'xʸ', inverse:'1/x', factorial:'n!', abs:'|x|', modulo:'mod', floor:'⌊x⌋', ceil:'⌈x⌉', round:'round',
    pi:'Pi', euler:'Euler', sqrt2:'Square root of 2', phi:'Golden ratio',
    lengthM:'Meter', lengthKm:'Kilometer', lengthCm:'Centimeter', lengthMi:'Mile', lengthFt:'Foot', lengthIn:'Inch',
    massKg:'Kilogram', massG:'Gram', massLb:'Pound', massOz:'Ounce',
    tempC:'Celsius', tempF:'Fahrenheit', tempK:'Kelvin',
    volL:'Liter', volMl:'Milliliter', volM3:'Cubic meter', volGal:'US gallon',
    timeS:'Second', timeMin:'Minute', timeH:'Hour', timeDay:'Day',
    referencePi:'π ≈ 3.141592653589793 — the ratio of a circle’s circumference to its diameter.',
    referenceE:'e ≈ 2.718281828459045 — the base of natural logarithms.',
    referenceGolden:'φ ≈ 1.618033988749895 — the golden ratio, the positive solution to x² − x − 1 = 0.',
    referenceConversions:'1 inch = 2.54 cm · 1 mile = 1.609344 km · 1 pound = 0.45359237 kg.',
    referenceSin:'sin(x) — the sine of angle x.',
    referenceCos:'cos(x) — the cosine of angle x.',
    referenceTan:'tan(x) — the tangent of angle x.',
    referenceLog:'log(x) — the common logarithm (base 10).',
    referenceLn:'ln(x) — the natural logarithm (base e).',
    referenceSquare:'x² — the square of x, or x multiplied by itself.',
    referenceSqrt:'√x — the principal square root of x.',
    referencePower:'xʸ — x raised to the power y.',
    referenceAngles:'Angles use degrees (DEG) or radians (RAD), according to the setting.',
  },
  es: {
    calculator:'Calculadora', subtitle:'Un instrumento pensado para las matemáticas diarias.', basic:'Modo básico', scientific:'Científica', advanced:'Avanzada',
    tools:'Herramientas', information:'Información',
    ready:'LISTA PARA CALCULAR', angle:'ÁNGULO', degrees:'DEG', radians:'RAD', memory:'Cálculo instantáneo', expression:'Expresión',
    history:'Historial', clear:'Borrar', noHistory:'El historial está vacío', historyHint:'Tus próximos cálculos aparecerán aquí.',
    converter:'Conversiones', convertHint:'Convierte unidades de uso diario.', quantity:'Magnitud', from:'De', to:'A', value:'Valor', result:'Resultado',
    length:'Longitud', mass:'Masa', temperature:'Temperatura', volume:'Volumen', time:'Tiempo',
    constants:'Constantes', constantsHint:'Selecciona una constante para insertarla en el cálculo.',
    references:'Referencias', referencesText:'Algunos datos útiles para tus cálculos.',
    about:'Acerca de', rules:'Reglas de cálculo', terms:'Términos del servicio', credits:'Créditos', settings:'Ajustes',
    aboutText:'Adam Calculator es una calculadora web personal diseñada y creada por Adam Eddahbi. Una herramienta discreta, rápida y fiable para el día a día, con funciones científicas a mano. Tus cálculos y ajustes permanecen en tu navegador.',
    rulesIntro:'La calculadora sigue las convenciones matemáticas habituales, sin aproximaciones ocultas.',
    ruleOrder:'Orden de las operaciones', ruleOrderText:'Primero se evalúan los paréntesis, después las funciones, las potencias, las multiplicaciones y divisiones, y por último las sumas y restas. Las potencias se asocian de derecha a izquierda.',
    rulePercent:'Porcentajes', rulePercentText:'El símbolo % convierte el valor anterior en una fracción sobre 100. Por ejemplo, 25% equivale a 0,25.',
    ruleAngles:'Ángulos', ruleAnglesText:'Las funciones trigonométricas usan DEG (grados) de forma predeterminada. Cambia a RAD para usar radianes.',
    ruleVerify:'Comprueba los resultados', ruleVerifyText:'Verifica por separado los resultados importantes antes de utilizarlos.',
    ruleResponsible:'Uso responsable', ruleResponsibleText:'Utiliza la herramienta con criterio y bajo tu propia responsabilidad.',
    ruleSecurity:'Uso del sitio', ruleSecurityText:'Está prohibido intentar interrumpir, dañar o eludir el funcionamiento del sitio.',
    termsText:'Adam Calculator es una herramienta personal gratuita, no un servicio prestado por una empresa. Al utilizar el sitio, aceptas estas condiciones. Puedes usar la calculadora para cálculos personales habituales. Los resultados se calculan localmente y pueden ser inexactos; verifícalos antes de confiar en ellos, especialmente en contextos profesionales, financieros o de seguridad. El servicio se ofrece sin garantías y su creador declina toda responsabilidad por las consecuencias de su uso, dentro de los límites legales. El nombre, el contenido y el código del sitio están sujetos a los derechos de sus respectivos titulares. El servicio o estas condiciones pueden cambiar sin previo aviso. No se garantiza la disponibilidad continua. Para cualquier consulta, ponte en contacto con su creador, Adam Eddahbi.',
    termsAcceptance:'Aceptación de las condiciones', termsAcceptanceText:'Al utilizar el sitio, aceptas estas condiciones.',
    termsUse:'Uso del servicio', termsUseText:'Puedes usar la calculadora para cálculos personales habituales. Está prohibido intentar interrumpir o eludir el funcionamiento del sitio.',
    termsAccuracy:'Exactitud de los resultados', termsAccuracyText:'Los resultados son orientativos y pueden contener errores o redondeos.',
    termsResponsibility:'Responsabilidad', termsResponsibilityText:'Verifica los resultados importantes. Dentro de los límites legales, el creador declina toda responsabilidad derivada del uso de la herramienta.',
    termsIntellectual:'Propiedad intelectual', termsIntellectualText:'El nombre, el contenido y el código están sujetos a los derechos de sus respectivos titulares. Adam Calculator no afirma ser una empresa registrada.',
    termsChanges:'Cambios del servicio', termsChangesText:'El servicio y estas condiciones pueden cambiar para corregir o mejorar la aplicación.',
    termsAvailability:'Disponibilidad', termsAvailabilityText:'El servicio se ofrece gratuitamente y sin garantía de funcionamiento o disponibilidad continuos.',
    termsContact:'Contacto', termsContactText:'Para cualquier consulta, contacta con el creador a través del canal del proyecto de Replit por el que recibiste la calculadora.',
    creditsText:'Adam Calculator — Creada por Adam Eddahbi. Desarrollada con cuidado para la web y con herramientas de código abierto. Gracias por usarla.',
    language:'Idioma', appearance:'Apariencia', darkMode:'Tema oscuro', darkHint:'Una paleta más suave para entornos con poca luz.',
    angleSetting:'Unidad angular', clearHistory:'Borrar el historial',
    animations:'Animaciones', animationsHint:'Transiciones sutiles entre interacciones.', close:'Cerrar', chooseLanguage:'Elige un idioma', light:'Claro', dark:'Oscuro',
    errorSyntax:'Expresión no válida', errorDivide:'No se puede dividir entre cero', errorDomain:'Valor fuera del dominio de la función', errorNumber:'El resultado no es finito',
    copy:'Copiar resultado', copied:'Copiado', clearEntry:'Borrar', delete:'Retroceso', allClear:'Borrar todo', decimal:'Decimal',
    menu:'Abrir menú', languageMenu:'Cambiar idioma', author:'Creado por Adam Eddahbi', copyright:'© 2026 Adam Calculator',
    sin:'sen', cos:'cos', tan:'tan', asin:'sen⁻¹', acos:'cos⁻¹', atan:'tan⁻¹', log:'log', ln:'ln', exp:'exp', sqrt:'√', square:'x²', power:'xʸ', inverse:'1/x', factorial:'n!', abs:'|x|', modulo:'mod', floor:'⌊x⌋', ceil:'⌈x⌉', round:'redondeo',
    pi:'Pi', euler:'Euler', sqrt2:'Raíz de 2', phi:'Proporción áurea',
    lengthM:'Metro', lengthKm:'Kilómetro', lengthCm:'Centímetro', lengthMi:'Milla', lengthFt:'Pie', lengthIn:'Pulgada',
    massKg:'Kilogramo', massG:'Gramo', massLb:'Libra', massOz:'Onza',
    tempC:'Celsius', tempF:'Fahrenheit', tempK:'Kelvin',
    volL:'Litro', volMl:'Mililitro', volM3:'Metro cúbico', volGal:'Galón US',
    timeS:'Segundo', timeMin:'Minuto', timeH:'Hora', timeDay:'Día',
    referencePi:'π ≈ 3,141592653589793 — relación entre la circunferencia y el diámetro de un círculo.',
    referenceE:'e ≈ 2,718281828459045 — base de los logaritmos naturales.',
    referenceGolden:'φ ≈ 1,618033988749895 — proporción áurea, solución positiva de x² − x − 1 = 0.',
    referenceConversions:'1 pulgada = 2,54 cm · 1 milla = 1,609344 km · 1 libra = 0,45359237 kg.',
    referenceSin:'sen(x) — seno del ángulo x.',
    referenceCos:'cos(x) — coseno del ángulo x.',
    referenceTan:'tan(x) — tangente del ángulo x.',
    referenceLog:'log(x) — logaritmo decimal (base 10).',
    referenceLn:'ln(x) — logaritmo natural (base e).',
    referenceSquare:'x² — el cuadrado de x, es decir, x multiplicado por sí mismo.',
    referenceSqrt:'√x — raíz cuadrada principal de x.',
    referencePower:'xʸ — x elevado a la potencia y.',
    referenceAngles:'Los ángulos se expresan en grados (DEG) o radianes (RAD), según el ajuste.',
  },
  ar: {
    calculator:'آلة حاسبة', subtitle:'أداة متقنة للحساب اليومي.', basic:'الوضع الأساسي', scientific:'علمي', advanced:'متقدم',
    tools:'الأدوات', information:'المعلومات',
    ready:'جاهزة للحساب', angle:'الزاوية', degrees:'درجة', radians:'راديان', memory:'حساب فوري', expression:'التعبير',
    history:'السجل', clear:'مسح', noHistory:'السجل فارغ', historyHint:'ستظهر عملياتك التالية هنا.',
    converter:'تحويل الوحدات', convertHint:'حوّل وحداتك اليومية بسهولة.', quantity:'الكمية', from:'من', to:'إلى', value:'القيمة', result:'النتيجة',
    length:'الطول', mass:'الكتلة', temperature:'درجة الحرارة', volume:'الحجم', time:'الوقت',
    constants:'الثوابت', constantsHint:'اختر ثابتاً لإضافته إلى العملية الحسابية.',
    references:'مراجع', referencesText:'معلومات مفيدة لحساباتك.',
    about:'حول التطبيق', rules:'قواعد الحساب', terms:'شروط الاستخدام', credits:'الشكر والتقدير', settings:'الإعدادات',
    aboutText:'Adam Calculator آلة حاسبة شخصية على الويب صممها وأنشأها Adam Eddahbi. أداة هادئة وسريعة وموثوقة للحساب اليومي، مع وظائف **…**

_This response is too long to display in full._
